# --- server
server:
  port: 9001
  servlet:
    context-path: /oauth2
  #jetty配置，主要是acceptors和selectors
  jetty:
    acceptors: 2
    selectors: 4

spring:
  application:
    name: oauth2-server
  redis:
    cluster:
      nodes: 20.26.37.179:28001,20.26.37.179:28002,20.26.37.180:28003,20.26.37.180:28004,20.26.37.181:28005,20.26.37.181:28006
    database: 0
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 1000000
  secondaryRedis:
    cluster:
      nodes: 20.26.37.179:28001,20.26.37.179:28002,20.26.37.180:28003,20.26.37.180:28004,20.26.37.181:28005,20.26.37.181:28006
    #      nodes:
    #        - 192.168.131.118:4883
    #        - 192.168.131.118:4884
    #        - 192.168.131.118:4885
    database: 0
    password:

logPath: logs

logging:
  level:
    root: DEBUG
    org.springframework.security: DEBUG
    com.quickstart: DEBUG
  file: ${logPath}/${spring.application.name}.log
