server:
  port: 9002
  servlet:
    context-path: /oauth2-client

security:
  oauth2:
    client:
      clientId: resourceServer1
      clientSecret: 123456
      accessTokenUri: http://localhost:9001/oauth2-server/oauth/token
      userAuthorizationUri: http://localhost:9001/oauth2-server/oauth/authorize
      authenticationScheme: query
      clientAuthenticationScheme: form
      registered-redirect-uri: http://localhost:8001/hello
    resource:
      tokenInfoUri: http://localhost:9001/oauth2-server/oauth/check_token
logging:
  level:
    org.springframework.security: DEBUG