server:
  port: 8085
spring:
  application:
    name: spring-activiti
  activiti:
    #1.flase： 默认值。activiti在启动时，会对比数据库表中保存的版本，如果没有表或者版本不匹配，将抛出异常
    #2.true： activiti会对数据库中所有表进行更新操作。如果表不存在，则自动创建
    #3.create_drop： 在activiti启动时创建表，在关闭时删除表（必须手动关闭引擎，才能删除表）
    #4.drop-create： 在activiti启动时删除原来的旧表，然后在创建新表（不需要手动关闭引擎）
    database-schema-update: true
    #记录历史等级 可配置的历史级别有none, activity, audit, full
    history-level: full
    #检测历史表是否存在，开启历史库
    db-history-used: true
    #校验流程文件，默认校验resources下的processes文件夹里的流程文件
    checkProcessDefinitions: false
    check-process-definitions: false # 自动部署验证设置:true-开启（默认）、false-关闭
  datasource:
    url: jdbc:mysql://localhost:3306/testactivitidb?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialization-mode: always
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: SELECT 1
  security:
    user:
      name: admin
      password: admin
swagger:
  enabled: true
