server:
  port: 8090

spring:
  profiles:
    active: dev
  application:
    name: oauth2-server

logging:
  level:
    root: DEBUG
    org.springframework.security: DEBUG
    com.quickstart: DEBUG
  file:
    name: logs/${spring.application.name}.log